Added limit and offset to the selection of questionnaires
waterstark/mir pull request #117
Opened 2023-12-12 03:50 UTC by ArtemStriver

Добавил limit и offset в функцию отображения списка questionnaire.

2023-12-12 13:24 UTC, MAKI1LOVE requested changes
нет тестов.
переделай поле page_n&mber через field и добавь ограничения (не отрицательное и меньше, например 5-7).
Также select-ится должны те люди, с которыми нет лайка

2023-12-14 11:14 UTC, ArtemStriver commented
Исправил типизацию page_number и реорганизовал модуль matches - перенес логику работы с базой данных в crud.

2023-12-15 09:47 UTC, MAKI1LOVE commented on src/likes/crud.py
> +async def _delete_like(session: AsyncSession, like: UserLike):
мы не в классе, поэтому нет нужды ставить нижние подчеркивания в начале. (это можно исправить прямо в графическом интрефейсе гита)

2023-12-15 09:48 UTC, MAKI1LOVE commented on src/matches/crud.py
> +        session: AsyncSession,
IDE автоматически ставит 8 пробелов. Мы решили делать 4

2023-12-15 09:50 UTC, MAKI1LOVE commented on src/likes/crud.py
> +async def _delete_like(session: AsyncSession, like: UserLike):
аналогично со всеми функциями ↓

2023-12-15 12:55 UTC, MAKI1LOVE commented on src/matches/crud.py
> +async def _change_questionnaire_match_info(query_result) -> None:
мне кажется, лучше избавиться от этого поля в возвращаемой схеме, т.к. данный эндпоинт возвращает итак все анкеты, с которыми произошел метч
Вопрос на обсуждение

2023-12-15 12:59 UTC, MAKI1LOVE commented on src/matches/crud.py
> +async def _get_all_matches(
не нужно

2023-12-15 13:01 UTC, MAKI1LOVE commented on src/matches/crud.py
> +async def _check_match_data(
сессия не нужна, аснхронная метка не нужна

2023-12-15 13:01 UTC, MAKI1LOVE commented on src/matches/crud.py
> +    matches = await _get_all_matches(session)
это должно быть переписано на sql

2023-12-15 13:02 UTC, MAKI1LOVE commented on src/matches/crud.py
> +async def delete_match_from_database(
from_database излишне. Откуда еще мы можем удалить сохраненный метч?

2023-12-15 13:10 UTC, MAKI1LOVE commented on src/matches/crud.py
> +    """Создание Метча и занесение его в базу данных Match."""
есть таблица match, а не бд. Не стоит это писать

2023-12-15 13:14 UTC, MAKI1LOVE commented on src/questionnaire/crud.py
> -async def get_list_questionnaire_first_10(
ты делаешь две несвязанные таски в одном PR

2023-12-15 13:15 UTC, MAKI1LOVE commented on src/questionnaire/routers.py
> +    page_number: Annotated[int, Path(ge=0)],
стоит ограничить до 5-7

2023-12-15 13:20 UTC, ArtemStriver commented on src/questionnaire/routers.py
> +    page_number: Annotated[int, Path(ge=0)],
Это же ограничение на отрицательные числа, ограничение на вывод количества объектов находится в crud в limit.

2023-12-15 13:20 UTC, MAKI1LOVE commented on src/matches/crud.py
> +async def get_match_by_match_id(
зачем решил изменить match_id с id?

2023-12-15 13:21 UTC, ArtemStriver commented on src/matches/crud.py
> +async def get_match_by_match_id(
Для большей ясности.

2023-12-15 13:22 UTC, MAKI1LOVE commented on src/questionnaire/routers.py
> +    "/get_list/{page_number}",
стоит заменить название эндпоинта на более осмысленное.
не стоит писать тип запроса в названии.
Смысл - мы ищем новые анкеты для лайка

2023-12-15 13:24 UTC, MAKI1LOVE commented on src/matches/crud.py
> +async def get_match_by_match_id(
> Для большей ясности.

получить метч по id - мне кажется, что понятно что id относится к метчу. Если хочешь, оставляй -_-

2023-12-16 15:51 UTC, MAKI1LOVE approved these changes
horosho

2023-12-16 15:54 UTC, MAKI1LOVE reviewed
все хорошо, но есть одно но
https://github.com/waterstark/mir/blob/4b19b72688fd4150ec9c13ce1bdad77ad49ceb1c/tests/with_db/test_questionnaire.py#L111
этот тест проходит?

2023-12-16 16:01 UTC, MAKI1LOVE commented on src/questionnaire/routers.py
> +    page_number: Annotated[int, Path(ge=0)],
> Это же ограничение на отрицательные числа, ограничение на вывод количества объектов находится в crud в limit.

пользователи не должны вечно просматривать анкеты. Должны быть лимиты + маломальская защита от парсинга

2023-12-16 16:10 UTC, ArtemStriver commented
Нет, т.к в последнем мердже Артур добавил этот тест, в нем надо изменить путь на /api/v1/questionnaire/list/0

2023-12-20 04:36 UTC, ArtemStriver commented
Исправил код. Теперь он соответствует PEP8, проверил через ruff. Тесты также проходят.

2023-12-20 16:39 UTC, MAKI1LOVE commented on src/matches/crud.py
> +        raise NotFoundException(
мы не должны прерывать удаление метча на этом этапе, ведь он существует.
+ нам не важно, был ли лайк в базе, если метч уже сформирован. Просто поробуем его удалить и все. Ошибкой не завершится. Главное, что удалим метч

2023-12-20 16:43 UTC, MAKI1LOVE commented on src/questionnaire/routers.py
> +    page_number: Annotated[int, Path(ge=0)],
в краде ты лучше оставь десять, а десятков анкет мы можем выдать пользователю только 3-5 за раз. Поэтому page_number должен быть ограничен

2023-12-20 16:45 UTC, MAKI1LOVE requested changes
все хорошо, только подправь замечания

2023-12-21 16:05 UTC, waterstark approved these changes

2023-12-21 16:05 UTC, merged