Added jwt to the questionnaire, updated the tests and added tests without jwt for questionnaire.
waterstark/mir pull request #124
Opened 2023-12-25 06:59 UTC by ArtemStriver

2023-12-31 13:43 UTC, MAKI1LOVE commented on src/questionnaire/routers.py
> +    dependencies=[Depends(current_user)],
Таким образом ты не проверяешь, что отправленная анкета принадлежит этому пользователю. Надо изменить анкету (убрать оттуда user_id) и получить юзера в аргументах

2023-12-31 13:45 UTC, MAKI1LOVE commented on src/questionnaire/routers.py
> +    dependencies=[Depends(current_user)],
аналогично ↑

2023-12-31 13:48 UTC, MAKI1LOVE requested changes
надо править

2024-01-02 13:59 UTC, MAKI1LOVE commented on tests/test_acceptance.py
> +        created_user_1_jwt = await get_jwt_strategy().write_token(AuthUser(**response.json()))
почему не работал authorized_cookie?

2024-01-02 14:10 UTC, MAKI1LOVE commented on tests/with_db/test_questionnaire.py
> +    questionary = await async_client.get(
почему из response не достается questionary?

2024-01-02 14:47 UTC, ArtemStriver commented on tests/test_acceptance.py
> +        created_user_1_jwt = await get_jwt_strategy().write_token(AuthUser(**response.json()))
jwt токен для authorized_cookie и для user, которого мы регистрируем отличаются, тем самым вызывая ошибку в тесте.

2024-01-02 14:52 UTC, ArtemStriver commented on tests/with_db/test_questionnaire.py
> +    questionary = await async_client.get(
Questionary, которая была раньше, из фикстур я понимаю, отличается от той, что выдается в response - firstname не совпадает. По этому я вынимаю существующую анкету, чтобы сравнить имя в ней с именем в response.

2024-01-06 10:33 UTC, MAKI1LOVE commented on tests/test_acceptance.py
> +        created_user_1_jwt = await get_jwt_strategy().write_token(AuthUser(**response.json()))
у тебя токен уже создался при регистрации. Тебе не нужно создавать новый.
В другом тесте есть аналогичная штука (только там кука после логина)
https://github.com/waterstark/mir/blob/2d01ee27c507dc976fa7887ce69786cb78c7f65a/tests/test_acceptance.py#L277

2024-01-06 11:24 UTC, ArtemStriver commented
Сделал получение токена как в test_acceptance_with_chat, для этого немного изменил порядок выполнения тестов.

2024-01-20 17:40 UTC, MAKI1LOVE approved these changes

2024-01-23 16:10 UTC, waterstark approved these changes

2024-01-23 16:10 UTC, merged