model_quest_change
waterstark/mir pull request #139
Opened 2024-02-15 08:23 UTC by pe4kahd

2024-02-15 19:52 UTC, MAKI1LOVE commented on src/matches/crud.py
баян

2024-02-15 20:14 UTC, MAKI1LOVE commented on src/questionnaire/schemas.py
> +    age: date
логичнее назвать birth(day), т.к. уже хранит дату рождения, а не кол-во лет
но вопрос на обсуждение

2024-02-15 20:15 UTC, MAKI1LOVE commented on src/questionnaire/schemas.py
> +    sport: str
тип перечисление должен быть

2024-02-15 20:17 UTC, MAKI1LOVE commented on src/questionnaire/crud.py
> +    today = date.today()
today.replace(year=today.year-18)
if questionaire.age > today: ...
и можно заменить название переменной today на какой-нибудь min_date

2024-02-15 20:19 UTC, MAKI1LOVE commented on tests/fixtures.py
> +"""Without that tests will die, sa cant work with date and pytest same time normaly(kostil)"""
что такое sa и kostil?
вообще, звучит как дичь. Есть ссылки на пруфы?

2024-02-15 20:20 UTC, MAKI1LOVE commented on tests/test_acceptance.py
> +             "id": IsUUID,
😡

2024-02-15 20:22 UTC, MAKI1LOVE commented on tests/test_matches.py
> +
?

2024-02-15 20:24 UTC, MAKI1LOVE commented on migrations/versions/fa5f9699e17b_new_quest_model.py
> +    op.add_column('user_questionnaire',  sa.Column('age', sa.Date(), nullable=True))
nullable=false

2024-02-22 13:53 UTC, MAKI1LOVE commented on src/questionnaire/crud.py
> +    today.replace(year=today.year - 18)
https://docs.python.org/3/library/datetime.html#datetime.date.replace

2024-02-22 14:12 UTC, MAKI1LOVE requested changes
нет теста на проверку работоспособности ограничения по возрасту

2024-02-24 16:09 UTC, waterstark approved these changes

2024-02-24 16:09 UTC, merged